name: FactionCraftPlugin
main: com.factioncraft.plugin.FactionCraftPlugin
version: 0.2.18
website: http://www.factioncraft.com
author: The FactionCraft Team
description: >
             Plugin adding faction gameplay (RPG-like) to minecraft. Developed and used by the unique and epic
             minecraft server community around factioncraft.com.
commands:
    factions:
        description: Shows a list of all available factions to join.
        usage: /<command>
    factioninfo:
        description: Shows information about a specific faction.
        usage: |
            /<command> <faction>
            Example: /<command> org - show information about the orc faction
    joinfaction:
        description: Lets you request a faction join. A mod/admin has to accept this request.
        usage: |
            /<command> <faction>
            Example: /<command> orc - you request to join the orc faction
    quitfaction:
        description: Admins can reset a player's faction.
        usage: |
            /<command> - resets your own faction
            /<command> [player] - resets the faction of [player]
    flagadmin:
        description: Admins can toggle whether they are seen as such.
        usage: |
            /<command> - toggles the flag
            /<command> [on|off] - sets the flag on or off
    flagop:
        description: OPs can toggle whether they are seen as such.
        usage: |
            /<command> - toggles the flag
            /<command> [on|off] - sets the flag on or off
    factionspawn:
        description: Manage faction spawns
        usage: |
            /<command> - teleports to player's faction's spawn (permission: 'factioncraft.factionspawn.own')
            /<command> <faction> - teleports to the <faction>'s spawn (permission: 'factioncraft.factionspawn.custom')
            /<command> <faction> set - sets the spawn for <faction> (permission: 'factioncraft.factionspawn.edit')
            /<command> <faction> unset - resets the spawn for <faction> (permission: 'factioncraft.factionspawn.edit')
    playerfaction:
        description: Print the faction of a player.
        usage: |
            /<command> - Print your own faction.
            /<command> <player> - Print <player>'s faction.

#  clear:
#    description: Clears your own or a player's inventory.
#    usage: |
#           /<command> [player]
#           Example: /<command> - clears your own inventory.
#           Example: /<command> Bukkit - clears Bukkit's inventory.
